name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libsystemd-dev
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}